### ISSUE TITLE
Styling the demo page

### ISSUE THREAD

**Issue by hackingbeauty** [insin/nwb#91] opened 2016-04-02 18:11 UTC
Hey, I'm using the following command to build the demo page for my component:

```
nwb build-demo
```

Everything works; however, I need to style my demo page.  

How can I add styles so that when I run the build-demo command my styles are included in the /dist folder?

Great tool btw.  Love nwb.

**Comment by insin** [comment] 2016-04-22 01:03
Duplicate of #72

**Closed by insin** 2016-04-22 01:03 UTC
Labels: support

**Comment by jorrit** [comment] 2017-08-20 08:30
CSS modules don't work out of the box for me, did you add something to webpack @novascreen ?

**Comment by novascreen** [comment] 2017-08-23 18:42
@jorrit yes, modules need to be enabled in the config:
https://github.com/novascreen/react-columns/blob/master/nwb.config.js
