### ISSUE TITLE
Using preact-compat with nwb

### ISSUE THREAD

**Issue by quentin-sommer** [insin/nwb#246] opened 2017-01-25 13:20 UTC
- [x] Bug report
- [ ] Feature request
- [x] Question / support request
- [ ] Other

nwb is installed globally
node : 7.4.0
npm : 4.1.1
nwb: 0.15.2

node_modules :
```
├── nwb@0.15.3
├── preact@7.2.0
├── preact-compat@3.11.0
└── semantic-ui-react@0.64.4
```
How can i use [preact-compat](https://github.com/developit/preact-compat) with nwb ? it works fine in development using this in `nwb.config.js`: 
```
module.exports = {
  type: 'preact-app',
  webpack: {
    aliases: {
      'react': 'preact-compat',
      'react-dom': 'preact-compat'
    }
  }
}
```
but at build it yields this error:
```
> nwb build-preact-app

✔ Cleaning app
✖ Building Preact app

Failed to compile with 1 error.

ERROR  in vendor.4acb2e33.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [./~/preact-compat/src/index.js:34,0][vendor.4acb2e33.js:6023,24]
```

**Comment by insin** [comment] 2017-01-25 13:30
It's already [configured for Preact apps by default](https://github.com/insin/nwb/blob/5d92a8a553fbfa7519ca8ac40d82c857a992424f/src/commands/build-preact-app.js#L38-L43) so you can reuse existing React components without any config, so try removing your `webpack.aliases` config.

This default setup is currently only [mentioned in the Quick Development guide](https://github.com/insin/nwb/blob/master/docs/guides/QuickDevelopment.md#reusing-react-modules), so I need to document it for `nwb` too.

The error is caused by `preact-compat` having a `module` entry in its `package.json` which results in Webpack 2 pulling in some untranspiled ES6 which UglifyJS can't handle (see #244).

**Comment by quentin-sommer** [comment] 2017-01-25 13:41
Seems like it's even better than I thought! Thanks for this project, by the way. It's exactly what I was looking for and it's been a pleasure to use up to now, I can edit the doc if you want!

**Comment by insin** [comment] 2017-01-25 13:59
Thanks, and enjoy 😋 

Closing in favour of #247, which contains actionable outcomes from this issue - I hadn't thought to add a config hint for this case, which could have told you this was already handled when you configured these aliases yourself.

**Closed by insin** 2017-01-25 13:59 UTC
Labels: support
