### ISSUE TITLE
Is that possible minify es6 code?

### ISSUE THREAD

**Issue by jswxwxf** [insin/nwb#395] opened 2017-10-25 03:21 UTC
I've configed the nwb.config.js as follows but doesn't work.

`
module.exports = {
  type: 'react-component',
  npm: {
    esModules: true,
    cjs: false,
    umd: false
  },
  babel: {
    stage: 0,
  },
  webpack: {
    uglify: {
      compress: {
        warnings: false
      },
      output: {
        comments: false
      },
      sourceMap: true
    }
  }
}
`

Thanks,
Jeffrey

**Comment by insin** [comment] 2017-10-31 05:02
Not currently, the version of UglifyJS being used by Webpack doesn't support ES6.

**Comment by insin** [comment] 2017-12-12 01:19
Closing as a dupe of #412 - uglifying ES6 will work in nwb v0.21

**Closed by insin** 2017-12-12 01:19 UTC
