### ISSUE TITLE
UMD fails to compile 

### ISSUE THREAD

**Issue by zsherman** [insin/nwb#391] opened 2017-10-14 16:37 UTC
This issue is a bug report.

I'm seeing UMD builds fail with the following error:

```
Unexpected token: punc ([) [./node_modules/react-docgen/dist/utils/getMemberValuePath.js:54,0][react-story.min.js:4497,2]
✖ Creating UMD builds
```

a quick google shows the cause might be an issue with babel presets, but adding a `.babelrc` isn't supported by nwb and trying to override the config with

```
babel: {
   "presets": ["es2015","react","stage-0"]
},
```

didn't seem to do the trick. Specifically it seems to be failing here https://github.com/reactjs/react-docgen/blob/master/src/utils/getMemberValuePath.js#L67.

You should be able to reproduce by cloning and building https://github.com/react-tools/react-story.

Any ideas @insin?

**Comment by insin** [comment] 2017-10-14 17:07
This is what it's complaining about in `react-docgen/dist/utils/getMemberValuePath.js`:

```js
var LOOKUP_METHOD = {
  [types.ArrowFunctionExpression.name]: _getMemberExpressionValuePath2.default,
  [types.FunctionExpression.name]: _getMemberExpressionValuePath2.default,
  [types.FunctionDeclaration.name]: _getMemberExpressionValuePath2.default,
  [types.VariableDeclaration.name]: _getMemberExpressionValuePath2.default,
  [types.ObjectExpression.name]: _getPropertyValuePath2.default,
  [types.ClassDeclaration.name]: _getClassMemberValuePath2.default,
  [types.ClassExpression.name]: _getClassMemberValuePath2.default
};
```

Computed property names are ES6 and the current version of UglifyJS being used by Webpack can't handle ES6, so it's causing the minified build to fail.

In the meantime, you can disable the minified build by adding a top-level `uglify: false` to your `nwb.config.js`.

**Comment by zsherman** [comment] 2017-10-14 17:18
Ah brilliant, thanks @insin!

**Comment by zsherman** [comment] 2017-10-26 21:00
seems like this issue was fixed? https://github.com/mishoo/UglifyJS2/issues/448

**Comment by zsherman** [comment] 2017-11-07 22:18
If babel is running before uglification, why would we be encountering this problem?

**Comment by insin** [comment] 2017-11-11 08:24
Babel isn't run on dependencies, only on your own code. This won't work until either Webpack switches to an ES-compatible version of UglifyJS or we switch to Rollup (#316) for bundling libraries.

**Comment by insin** [comment] 2017-12-12 01:18
Closing as a dupe of #412 - uglifying ES6 will work in nwb v0.21

**Closed by insin** 2017-12-12 01:18 UTC
